### ISSUE TITLE
[mongoDB] password in Document message ?

### ISSUE THREAD

**Issue by anonprophet** [julisman/lokochat#2]
halo mas agung,
saya sudah beli bukunya

masih bingung ada field password di Document message??

itu digunakan untuk apa ya, bukannya tidak pakai password saat mengirim pesan ke teman ?

thanks

**Comment by julisman** [comment]
field password yang dimana mas ?

**Comment by anonprophet** [comment]
di hal. 175 Desain Skema MongoDB

### document message

| Key | Type |
| --- | --- |
| _id | ObjectId |
| from | String |
| fromname | String |
| **password** | String |
| to | String |
| message | String |
| time | String |

perbedaan **from** dan **fromname** apa ya mas?

apakah benar **from** untuk menyimpan **_id** _user_ dri pengirim pesan,
sedangkan **fromname** untuk menyimpan **nama** _user_ pengirim pesan

maaf saya banyak tanya, lagi ingin mendalami supaya bisa dikembangkan untuk skripsi

**Comment by julisman** [comment]
oh itu tidak di perlukan mas , mungkin ada kesalahan. sorry

**Comment by anonprophet** [comment]
thanks om @julisman ,
tolong jawab yg pertanyaan ke2 mas ..

**Comment by julisman** [comment]
field password yg mana ya mas ?

Sent from Yahoo Mail on Android

**Comment by anonprophet** [comment]
owh, dari email ya mas. soalnya saya update pertanyaannya di github..
